# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Run the directions.py script when the container launches
CMD ["sh", "-c", "while true; do python3 directions.py; sleep 1; done"]
